### PR TITLE
Update trac 1.4.4

### PR DESCRIPTION
**Pull request by bmispelon**
Most of the work is from Florian's original PR: https://github.com/django/code.djangoproject.com/pull/133

In addition, I made the following changes:
* removed warnings about missing js files (Florian deleted them but left the `<script>` tags in the html)
* bumped version for Trac (1.4.4 instead of 1.4.3 and a slightly more recent version of the xmlrpc plugin)
* fixed a styling issue with bold text in the navigation
* updated the `box-shadow` scss reset, and created the `noshadows.py` script to automate that task. The script has some builtin tests when called with `--tests`, not sure if it's worth adding those to CI too.

Trac being trac, my local testing on a blank instance was limited but I think this PR is good enough to be merged. I'd like to continue the upgrade work once this is merged so we can finally move off Python 2 and Django 1.11 🧓🏻 .

Here are a few random tips that helped me test things locally:
* turn on more verbose logging in `trac.ini` (I used `log_level = INFO` and `log_type = stderr`)
* comment out the `[notification]` and `[notification-subscriber]` sections in `trac.ini` to avoid errors while sending emails after ticket creation/update

### CODE REVIEW

**Comment by felixxm** [comment]
I applied `black`, please rebase.

**Comment by bmispelon** [comment]
> I applied `black`, please rebase.

PR rebased and ready to test (I also noticed and fixed a styling issue where the ticket box had lost its themed background color)

**Comment by bmispelon** [comment]
Issue #141 will also be fixed by merging this

**Comment by felixxm** [comment]
I merged 42216093fdb86b9c3f54fffc3697fbaac71bd961 because it's compatible with Trac 1.2.6.

**Comment by felixxm** [comment]
@bmispelon I'm looking at 39e46f726b5b1c7c68e181be45076569b9519e6b. Do you think we can remove these files in advance? i.e. is it compatible with 1.2.6?

**Comment by bmispelon** [comment]
> @bmispelon I'm looking at [39e46f7](https://github.com/django/code.djangoproject.com/commit/39e46f726b5b1c7c68e181be45076569b9519e6b). Do you think we can remove these files in advance? i.e. is it compatible with 1.2.6?

I'm not sure it's safe to delete all of them (looking at `mobile-menu.js` for example, it seems it's used to generate the navigation menu for the mobile version). I'm going to try and investigate which files are currently unused (or safe to delete) so we could minimize the diff. I'll keep you posted.

**Comment by bmispelon** [comment]
Here's a PR that removes the js files that were not used: #149 

Once that one is merged, I'll rebase this one and resolve the conflicts that arise.

**Comment by bmispelon** [comment]
@felixxm I've rebased this branch after the merging of #149 . I've taken the liberty to squash some commits together when I thought it made sense, I hope that's ok (if not let me know and I'll try to undo my git mess 😅 ). Hopefully that makes the reviewing easier.

**Comment by felixxm** [comment]
Let's try, merged :boom:

**Comment by felixxm** [comment]
and deployed :crossed_fingers:

**Pull request closed without merging**
