### PR TITLE
Fixed #27 -- Made trac-ticket-buttons be displayed above quote blocks

### LINKED ISSUE #27: Quotation in ticket comment can hide comment action buttons
See https://code.djangoproject.com/ticket/24096#comment:6
issue #22 may be related.
(couldn't get the image to upload for some reason... this one is from a different ticket, url updated)

### PR DESCRIPTION
**Pull request by bmispelon**
We now have the opposite problem: if the first line of the quoted text is long enough, it can get obscured by the buttons:

1_ some_documentation_examples_incorrectly_use_w_to_match_against_slugs_in_urls _ _django_-_2015-04-27_13 37 23

I still think that's an improvement though.

### CODE REVIEW

**Comment by timgraham** [comment]
Maybe try position the buttons a bit higher so they might overlap the quote but not the text in it?

**Comment by bmispelon** [comment]
Actually, while playing around with `position: relative` I ended up in a configuration where the text from the quote flows around the buttons:
1_ some_documentation_examples_incorrectly_use_w_to_match_against_slugs_in_urls _ _django_-_2015-04-27_14 17 25

It's still not very pretty but I think it's a definite improvement.

**Comment by timgraham** [comment]
LGTM

**Comment by shaib** [comment]
The picture LGTM, but that's not the code that's currently in the PR, is it?

**Comment by bmispelon** [comment]
@shaib: The last picture is what's in the PR as far as I can tell.

**Pull request merged**
