### PR TITLE
Renamed trac.ini, built psycopg2 from source

### PR DESCRIPTION
**Pull request by tobiasmcnulty**
**For review only!** Please don't merge until the AWS migration is complete.

- `trac.ini` is renamed to `trac.ini.prod` so we don't need to edit a git-tracked file when deploying. A copy will need to be made for local development as well (the README is updated to indicate as much).
- On Ubuntu 20.04, `psycopg2` needs to be built from source to avoid a uwsgi segfault (https://stackoverflow.com/a/54253374/166053)

```
Mon Feb  7 08:26:29 2022 - !!! uWSGI process 10953 got Segmentation Fault !!!
Mon Feb  7 08:26:29 2022 - *** backtrace of 10953 ***
trac|uWSGI worker 2(uwsgi_backtrace+0x33) [0x5608b91aad83]
trac|uWSGI worker 2(uwsgi_segfault+0x27) [0x5608b91ab197]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f6a435ec210]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/./libssl-1d6df745.so.1.0.2p(ssl3_cleanup_key_block+0xb) [0x7f6a3f221cab]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/./libssl-1d6df745.so.1.0.2p(ssl3_clear+0x16) [0x7f6a3f21f5a6]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/./libssl-1d6df745.so.1.0.2p(tls1_clear+0x9) [0x7f6a3f22b219]
/lib/x86_64-linux-gnu/libssl.so.1.1(SSL_new+0x493) [0x7f6a43c67643]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/libpq-3a62a61f.so.5.11(+0x23969) [0x7f6a3f4b6969]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/libpq-3a62a61f.so.5.11(+0x24fc5) [0x7f6a3f4b7fc5]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/libpq-3a62a61f.so.5.11(PQconnectPoll+0xb78) [0x7f6a3f4a1ba8]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/libpq-3a62a61f.so.5.11(+0xfa28) [0x7f6a3f4a2a28]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/.libs/libpq-3a62a61f.so.5.11(PQconnectdb+0x1f) [0x7f6a3f4a541f]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0x12511) [0x7f6a3f6f6511]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0x1329f) [0x7f6a3f6f729f]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x159981) [0x7f6a4146c981]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(_PyObject_CallFunction_SizeT+0xc2) [0x7f6a414ce732]
/home/www/trac/venv/lib/python2.7/site-packages/psycopg2/_psycopg.so(+0xc1b8) [0x7f6a3f6f01b8]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x64d2) [0x7f6a4142ae82]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x70e9) [0x7f6a4142ba99]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x190f6f) [0x7f6a414a3f6f]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1a711c) [0x7f6a414ba11c]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1561c7) [0x7f6a414691c7]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x159981) [0x7f6a4146c981]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x2a3a) [0x7f6a414273ea]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x191037) [0x7f6a414a4037]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x1119) [0x7f6a41425ac9]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x70e9) [0x7f6a4142ba99]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x70e9) [0x7f6a4142ba99]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x70e9) [0x7f6a4142ba99]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x190f6f) [0x7f6a414a3f6f]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1a711c) [0x7f6a414ba11c]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_CallFunctionObjArgs+0x12f) [0x7f6a414ce04f]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x4f64) [0x7f6a41429914]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x96f4) [0x7f6a4142e0a4]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x70e9) [0x7f6a4142ba99]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x70e9) [0x7f6a4142ba99]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x70e9) [0x7f6a4142ba99]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x808) [0x7f6a41424308]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x190f6f) [0x7f6a414a3f6f]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1a711c) [0x7f6a414ba11c]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(+0x1aa9c6) [0x7f6a414bd9c6]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyObject_Call+0x57) [0x7f6a414cde97]
/lib/x86_64-linux-gnu/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x48) [0x7f6a41423868]
/usr/lib/uwsgi/plugins/python27_plugin.so(python_call+0x16) [0x7f6a41697b66]
/usr/lib/uwsgi/plugins/python27_plugin.so(uwsgi_request_wsgi+0x139) [0x7f6a41699f79]
*** end of backtrace ***
Mon Feb  7 08:26:30 2022 - DAMN ! worker 2 (pid: 10953) died :( trying respawn ...
Mon Feb  7 08:26:30 2022 - Respawned uWSGI worker 2 (new pid: 10983)
```

### CODE REVIEW

**Comment by apollo13** [comment]
We should then also (after the migration) renew the askimet and captcha keys.

**Comment by felixxm** [comment]
Do we have to remove `trac.ini` from this repository? This will make local development difficult.

**Comment by tobiasmcnulty** [comment]
>

**Comment by tobiasmcnulty** [comment]
> Do we have to remove `trac.ini` from this repository? This will make local development difficult.

Hm, good point. I suppose we could keep it here and either rename it so we're not modifying a file in git for the deploy, or modify it in place, add `force: yes` to the git update, and re-deploy the prod changes on each deploy (e.g., via `lineinfile`)?

**Comment by tobiasmcnulty** [comment]
> > Do we have to remove `trac.ini` from this repository? This will make local development difficult.
> 
> Hm, good point. I suppose we could keep it here and either rename it so we're not modifying a file in git for the deploy, or modify it in place, add `force: yes` to the git update, and re-deploy the prod changes on each deploy (e.g., via `lineinfile`)?

I've gone ahead with this. We could add new keys through the same approach.

**Comment by tobiasmcnulty** [comment]
Switching to Docker/Podman instead: #121

**Pull request closed without merging**
