### PR TITLE
Rename Git branch "master" to "main"

### PR DESCRIPTION
**Pull request by MarkusH**
This change follows a long discussion on django-develops [1].

[1] https://groups.google.com/g/django-developers/c/tctDuKUGosc/

Refs django/django#14048

### CODE REVIEW

**Review by manfre — APPROVED** [review]
Thank you for taking this on

**Comment by adamchainz** [comment]
I noticed there's this ticket version selector too, maybe in the DB?

Screenshot 2021-03-04 at 19 12 01

**Comment by MarkusH** [comment]
Thanks Adam. That's not going to be a simple change. Unless we do a `UPDATE t SET version = 'main' WHERE version = 'master'` directly in PostgreSQL.

**Comment by adamchainz** [comment]
Presumably we can change what is visible in the drop down since someone adds the new versions of Django as they come out? Also that query doesn't look so bad..

**Comment by felixxm** [comment]
I've changed `master` to `dev`.

**Comment by MarkusH** [comment]
Thanks @felixxm !

**Pull request merged**
