### PR TITLE
Fixed #127 -- Updated PostgreSQL to 14 in docker-compose.

### LINKED ISSUE #127: Upgrade PostgreSQL to version 14
From the Django Ops team, we'll be upgrade PostgreSQL to version 14. We'll update here when the process is done.

- [ ] https://github.com/django/code.djangoproject.com/blob/db2c40656cd61de85626c87331df59528847344e/docker-compose.yml#L20

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Review by bmispelon — APPROVED** [review]
Had to make the following changes to get `docker-compose up` to work locally for me:
```diff
     build:
       context: ./
       dockerfile: Dockerfile
-    command: ["/venv/bin/tracd", "--port", "9000", "-s", "trac-env"]
+    command: ["/venv/bin/gunicorn", "--bind", "0.0.0.0:9000", "--workers=1", "--reload", "tracdjangoplugin.wsgi:application"]
     environment:
      - TRAC_INI_database=postgres://code.djangoproject:secret@db/code.djangoproject
+     - SECRETS_FILE=/code/secrets.json
+     - TRAC_ENV=/code/trac-env
     volumes:
       - ./:/code/
     ports:
```

Otherwise everything seems to work, but I'm not sure what to test exactly. I did load the `trac.sql` from djangoproject.com and that appeared to work.

**Comment by felixxm** [comment]
> Had to make the following changes to get `docker-compose up` to work locally for me:

Is it somehow related with PostgreSQL version? :thinking:

**Comment by bmispelon** [comment]
> > Had to make the following changes to get `docker-compose up` to work locally for me:
> 
> Is it somehow related with PostgreSQL version? 🤔

Almost definitely not, I think it's the changes i made to the plugin system in eb16ed0b13ec81d1c798599683ea7fba391c2053. Not sure what consequences it has to change the postgres version. I assume it's to do with the way that's deployed in prod?

**Comment by felixxm** [comment]
> Not sure what consequences it has to change the postgres version. I assume it's to do with the way that's deployed in prod?

Yes, I checked and we're already using PostgreSQL 14. The only difference is that now the "local" `psql` client is in version 12 instead of 14.

**Pull request merged**
