### PR TITLE
Disabled spamhaus.org antispam check

### PR DESCRIPTION
**Pull request by bmispelon**
The service doesn't seem to work, possibly because
of the containerization.

Refs #245

### CODE REVIEW

**Review by timgraham — APPROVED** [review]
Are you sure it's going to be temporary?

**Comment by bmispelon** [comment]
> Are you sure it's going to be temporary?

I meant "temporary" as in "until we remove it from the config again". The changes here will definitely survive reboots/redeploys.

Did I misunderstand your proposed resolution from the ticket?

**Comment by timgraham** [comment]
I just meant, I'm not sure we need to try to fix the underlying problem and add the list back.

**Comment by bmispelon** [comment]
> I just meant, I'm not sure we need to try to fix the underlying problem and add the list back.

Ah I see, yeah that's a good point. Ideally I'd like to fix the underlying issue, but if disabling `spamhaus` doesn't cause any major issues then I don't think I'll want to spend resources on trying to dig (hehe) further.

I'll change the wording not to mention the fix being temporary 👍🏻

**Review by carltongibson — APPROVED** [review]

**Pull request merged**
