### PR TITLE
Apply prettier to css files

### PR DESCRIPTION
**Pull request by ulgens**
Coming from https://github.com/django/code.djangoproject.com/pull/238#discussion_r1883809067

### CODE REVIEW

**Comment by ulgens** [comment]
@bmispelon Not sure how to proceed with this one, waiting for your input.

**Comment by bmispelon** [comment]
Thanks for adding this!

I don't think `output.css` should be reformatted, since it's compiled from the files in the `scss` directory (I think that means we can keep ignoring the `css` files in the prettier hook).
Similarly with `webfont.js`: from what I understand it's a vendored library that we just copied in to the project, so I would rather not touch it.

But everything else I'm up for autoformatting 👍🏻

**Comment by bmispelon** [comment]
https://github.com/django/djangoproject.com/pull/1838 added a prettier config for djangoproject.com, I suggest we adopt the same rules here

**Comment by ulgens** [comment]
@bmispelon https://github.com/django/code.djangoproject.com/pull/248 🎈

**Comment by ulgens** [comment]
> I don't think `output.css` should be reformatted, since it's compiled from the files in the `scss` directory (I think that means we can keep ignoring the `css` files in the prettier hook).

After the import of prettier config for JS and a rebase, the only change left in the branch is `output.css` file. I agree about ignoring css files, and it lefts nothing to merge. I'm closing the PR.

**Pull request closed without merging**
